Repository YAPP-Github/Showpot-BE, pull requests merged in 2024-08, with the labels that each got.

#68 test : show domain query
  app/api/show-api/src/main/java/com/example/genre/service/dto/request/GenreSubscriptionPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/request/GenreUnsubscriptionPaginationServiceRequest.java
  app/api/show-api/src/test/java/artist/service/ArtistServiceTest.java
  app/api/show-api/src/test/java/genre/service/GenreServiceTest.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/request/GenreSubscriptionPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/request/GenreUnsubscriptionPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/repository/artist/ArtistQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/genre/GenreQuerydslRepositoryImpl.java
  app/domain/show-domain/src/test/java/org/example/domain/ShowTest.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistSearchRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/genre/GenreRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowSearchRepositoryTest.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ArtistFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ArtistGenreFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/GenreFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/dto/ArtistRequestDtoFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/dto/GenreRequestDtoFixture.java
Labels: feat

#64 test : show domain 단위 테스트
  app/api/show-api/build.gradle
  app/api/show-api/src/main/java/com/example/artist/service/ArtistService.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/request/GenreSubscriptionPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/request/GenreUnsubscriptionPaginationServiceRequest.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistDtoFixture.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistRequestDtoFixture.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistResponseDtoFixture.java
  app/api/show-api/src/test/java/artist/service/ArtistAdminServiceTest.java
  app/api/show-api/src/test/java/artist/service/ArtistServiceTest.java
  app/api/show-api/src/test/java/genre/fixture/GenreRequestDtoFixture.java
  app/api/show-api/src/test/java/genre/fixture/GenreResponseDtoFixture.java
  app/api/show-api/src/test/java/genre/service/GenreServiceTest.java
  app/api/show-api/src/test/java/show/fixture/dto/ShowRequestDtoFixture.java
  app/api/show-api/src/test/java/show/fixture/dto/ShowResponseDtoFixture.java
  app/api/show-api/src/test/java/show/service/ShowAdminServiceTest.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/show-domain/build.gradle
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/ArtistFilterDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/ArtistSubscriptionDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/ArtistUnsubscriptionDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/SimpleArtistDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/request/GenreSubscriptionPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/request/GenreUnsubscriptionPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/response/GenreSubscriptionDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/response/GenreUnsubscriptionDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowSearchDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/repository/artist/ArtistQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/genre/GenreQuerydslRepositoryImpl.java
  app/domain/show-domain/src/test/java/org/example/domain/ShowTest.java
  app/domain/show-domain/src/test/java/org/example/fixture/ArtistFixture.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistSearchRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/genre/GenreRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowSearchRepositoryTest.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ArtistFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ArtistGenreFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/GenreFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/dto/ArtistRequestDtoFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/dto/GenreRequestDtoFixture.java
  app/domain/user-domain/build.gradle
  app/domain/user-domain/src/testFixtures/java/org/example/fixture/ArtistSubscriptionFixture.java
  app/domain/user-domain/src/testFixtures/java/org/example/fixture/GenreSubscriptionFixture.java
Labels: feat

#66 fix : 아티스트 성별 중 혼성 추가
  app/api/show-api/src/main/java/com/example/artist/vo/ArtistGenderApiType.java
  app/api/user-api/src/main/resources/templates/artist_create_form.html
  app/api/user-api/src/main/resources/templates/artist_form.html
  app/api/user-api/src/main/resources/templates/artist_list_form.html
  app/domain/show-domain/src/main/java/org/example/vo/ArtistGender.java
Labels: fix

#71 feat: 공연 상세 조회
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/param/ShowTicketingSiteApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowCreateApiForm.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowUpdateApiForm.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/SeatInfoApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowArtistApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowDetailApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowGenreApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInfoApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowSeatApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TicketingInfoApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/vo/TicketingApiType.java
  app/api/show-api/src/main/java/com/example/show/service/ShowAdminService.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/param/ShowSearchPaginationServiceParam.java
  app/api/show-api/src/main/java/com/example/show/service/dto/param/ShowTicketingSiteServiceParam.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowCreateServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowUpdateServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowArtistServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowDetailServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowGenreServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowInfoServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowSeatServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/error/ShowError.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistDtoFixture.java
  app/api/show-api/src/test/java/show/fixture/dto/ShowDtoFixture.java
  app/api/show-api/src/test/java/show/service/ShowAdminServiceTest.java
  app/api/user-api/src/main/resources/templates/show_create_form.html
  app/api/user-api/src/main/resources/templates/show_form.html
  app/api/user-api/src/main/resources/templates/show_list_form.html
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/ArtistDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/response/GenreDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowCreationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDetailDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowInfoDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowSearchDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/entity/show/Show.java
  app/domain/show-domain/src/main/java/org/example/entity/show/ShowSearch.java
  app/domain/show-domain/src/main/java/org/example/entity/show/ShowTicketingTime.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/SeatPrices.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/Ticketing.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/TicketingSites.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowTicketingTimeRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showsearch/ShowSearchQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/show-domain/src/main/java/org/example/vo/TicketingType.java
  app/domain/show-domain/src/test/java/org/example/fixture/ShowFixture.java
Labels: feat

#82 fix : dev환경 redis 도커 컨테이너 연결
  app/src/main/resources/application-dev.yml
Labels: fix

#90 feat : Efficient Dockerfile
  dockerfile-dev
  dockerfile-prod
Labels: feat

#84 fix : 공연 상세 조회 리스트 쿼리 수정
  app/api/show-api/src/main/java/com/example/artist/service/ArtistAdminService.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/response/ArtistKoreanNameWithShowIdServiceResponse.java
  app/api/show-api/src/main/java/com/example/genre/service/GenreAdminService.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/response/GenreNameWithShowIdServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowAdminController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInfoApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowWithTicketingTimesServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/ShowAdminService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowInfoServiceResponse.java
  app/api/show-api/src/test/java/show/service/ShowAdminServiceTest.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/response/ArtistKoreanNamesWithShowIdDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/genre/response/GenreNamesWithShowIdDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowWithTicketingTimesDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showartist/ShowArtistQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showartist/ShowArtistQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showartist/ShowArtistRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showgenre/ShowGenreQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showgenre/ShowGenreQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showgenre/ShowGenreRepository.java
  app/domain/show-domain/src/main/java/org/example/usecase/artist/ArtistUseCase.java
  app/domain/show-domain/src/main/java/org/example/usecase/genre/GenreUseCase.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowArtistRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowGenreRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowRepositoryTest.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowArtistFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowGenreFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowTicketingTimeFixture.java
Labels: fix

#87 feat : 유저 프로필 기능 구현
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/user-api/build.gradle
  app/api/user-api/src/main/java/org/example/controller/UserController.java
  app/api/user-api/src/main/java/org/example/controller/dto/response/UserProfileApiResponse.java
  app/api/user-api/src/main/java/org/example/service/UserService.java
  app/api/user-api/src/main/java/org/example/service/dto/request/LoginServiceRequest.java
  app/api/user-api/src/main/java/org/example/service/dto/response/UserProfileServiceResponse.java
  app/api/user-api/src/main/java/org/example/vo/SocialLoginApiType.java
  app/api/user-api/src/test/java/org/example/fixture/dto/UserRequestDtoFixture.java
  app/api/user-api/src/test/java/org/example/service/UserServiceTest.java
  app/domain/common-domain/src/main/resources/schema.sql
  app/domain/user-domain/src/main/java/org/example/dto/response/UserProfileDomainResponse.java
  app/domain/user-domain/src/main/java/org/example/entity/User.java
  app/domain/user-domain/src/main/java/org/example/repository/user/UserQuerydslRepository.java
  app/domain/user-domain/src/main/java/org/example/repository/user/UserQuerydslRepositoryImpl.java
  app/domain/user-domain/src/main/java/org/example/usecase/UserUseCase.java
  app/domain/user-domain/src/main/java/org/example/vo/RandomNickname.java
  app/domain/user-domain/src/test/java/org/example/QueryTest.java
  app/domain/user-domain/src/test/java/org/example/ShowDomainTestConfiguration.java
  app/domain/user-domain/src/test/java/org/example/repository/UserRepositoryTest.java
  app/domain/user-domain/src/test/resources/application-user-domain-test.yml
  app/domain/user-domain/src/testFixtures/java/org/example/fixture/SocialLoginFixture.java
  app/domain/user-domain/src/testFixtures/java/org/example/fixture/UserFixture.java
Labels: feat

#91 fix : 아티스트 구독하지 않은 목록 인증/인가 수정
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/artist/controller/ArtistController.java
  app/api/show-api/src/main/java/com/example/artist/controller/dto/request/ArtistUnsubscriptionPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistService.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/request/ArtistUnsubscriptionPaginationServiceRequest.java
  app/api/show-api/src/test/java/artist/service/ArtistServiceTest.java
Labels: feat

#93 feat: 공연 목록 조회
  app/api/show-api/src/main/java/com/example/artist/controller/dto/request/ArtistSearchPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/artist/controller/dto/request/ArtistSubscriptionPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/artist/controller/dto/request/ArtistUnsubscriptionPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistAdminService.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistService.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/request/ArtistSearchPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/request/ArtistSubscriptionPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/request/ArtistUnsubscriptionPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/artist/vo/ArtistSortApiType.java
  app/api/show-api/src/main/java/com/example/artist/vo/ArtistSortStandardApiType.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowAlertPaginationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowArtistPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowArtistSimpleApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowGenrePaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowGenreSimpleApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInterestPaginationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowPaginationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowSimpleApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowTicketingTimePaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/vo/ShowSortApiType.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowArtistSimpleServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowDetailServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowGenreSimpleServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowPaginationServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowTicketingTimeServiceParam.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistRequestDtoFixture.java
  app/domain/common-domain/src/main/resources/application-domain-dev.yml
  app/domain/common-domain/src/main/resources/application-domain-local.yml
  app/domain/common-domain/src/main/resources/data.sql
  app/domain/common-domain/src/main/resources/schema.sql
  app/domain/show-domain/src/main/java/org/example/dto/artist/request/ArtistPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/request/ArtistSearchPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowCreationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDetailDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowPaginationDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/entity/show/Show.java
  app/domain/show-domain/src/main/java/org/example/entity/show/ShowTicketingTime.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/SeatPrices.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/ShowTicketingTimes.java
  app/domain/show-domain/src/main/java/org/example/entity/show/info/TicketingSites.java
  app/domain/show-domain/src/main/java/org/example/repository/artist/ArtistQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/artist/artistsearch/ArtistSearchQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/show-domain/src/main/java/org/example/vo/ArtistSortType.java
  app/domain/show-domain/src/main/java/org/example/vo/ShowSortType.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/artist/ArtistSearchRepositoryTest.java
  app/domain/show-domain/src/test/java/org/example/repository/show/ShowRepositoryTest.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/domain/ShowFixture.java
  app/domain/show-domain/src/testFixtures/java/org/example/fixture/dto/ArtistRequestDtoFixture.java
  common/src/main/java/org/example/util/DateTimeUtil.java
Labels: feat

#95 feat: 공연 목록 조회
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInfoApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowInfoServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowPaginationServiceResponse.java
  app/domain/common-domain/src/main/java/org/example/util/SliceUtil.java
  app/domain/common-domain/src/main/resources/data.sql
  app/domain/common-domain/src/main/resources/schema.sql
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDetailDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/entity/show/Show.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  common/src/main/java/org/example/util/DateTimeUtil.java
Labels: feat

#97 fix : docker compose dev
  .github/workflows/showpot-dev-cd.yml
  docker-compose-dev.yml
Labels: fix

#98 fix : 레디스 네트워크 연동
  .github/workflows/showpot-dev-cd.yml
  app/src/main/resources/application-dev.yml
  docker-compose-dev.yml
Labels: fix

#100 feat : 토큰 재발급 API 추가
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/common-api/src/main/java/org/example/filter/JWTFilter.java
  app/api/common-api/src/main/java/org/example/security/token/TokenProcessor.java
  app/api/user-api/src/main/java/org/example/controller/UserController.java
  app/api/user-api/src/main/java/org/example/controller/dto/request/LogoutApiRequest.java
  app/api/user-api/src/main/java/org/example/controller/dto/request/ReissueApiRequest.java
  app/api/user-api/src/main/java/org/example/controller/dto/request/WithdrawalApiRequest.java
  app/api/user-api/src/main/java/org/example/controller/dto/response/ReissueApiResponse.java
  app/api/user-api/src/main/java/org/example/service/UserService.java
  app/api/user-api/src/main/java/org/example/service/dto/request/ReissueServiceRequest.java
Labels: feat

#105 feat: 관심 공연
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowInterestPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/InterestShowPaginationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInterestApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInterestPaginationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowTicketingTimeApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowTicketingTimePaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/InterestShowPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowInterestServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/InterestShowPaginationServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowInterestServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowPaginationServiceResponse.java
  app/api/show-api/src/test/java/artist/fixture/dto/ArtistRequestDtoFixture.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/common-domain/src/main/resources/schema.sql
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowRepository.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/user-domain/src/main/java/org/example/config/UserDomainConfig.java
  app/domain/user-domain/src/main/java/org/example/dto/request/InterestShowDomainRequest.java
  app/domain/user-domain/src/main/java/org/example/dto/request/InterestShowPaginationDomainRequest.java
  app/domain/user-domain/src/main/java/org/example/dto/response/InterestShowPaginationDomainResponse.java
  app/domain/user-domain/src/main/java/org/example/entity/InterestShow.java
  app/domain/user-domain/src/main/java/org/example/repository/interest/InterestShowQuerydslRepository.java
  app/domain/user-domain/src/main/java/org/example/repository/interest/InterestShowQuerydslRepositoryImpl.java
  app/domain/user-domain/src/main/java/org/example/repository/interest/InterestShowRepository.java
  app/domain/user-domain/src/main/java/org/example/usecase/UserShowUseCase.java
  common/src/main/java/org/example/util/DateTimeUtil.java
Labels: feat

#107 feat : 공연 티켓팅 알림 등록 및 조회
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/publish/MessagePublisher.java
  app/api/show-api/src/main/java/com/example/publish/message/ReserveShowServiceMessage.java
  app/api/show-api/src/main/java/com/example/publish/message/TicketingAlertsToReserveServiceMessage.java
  app/api/show-api/src/main/java/com/example/publish/message/TicketingReservationServiceMessage.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowAlertRegistrationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/TicketingAlertReservationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TicketingAlertReservationApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TicketingAlertReservationAvailabilityApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TicketingAlertReservationStatusApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/vo/ShowAlertTimeApiType.java
  app/api/show-api/src/main/java/com/example/show/controller/vo/TicketingAlertTimeApiType.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/TicketingAlertReservationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/TicketingAlertReservationAvailabilityServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/TicketingAlertReservationServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/TicketingAlertReservationStatusServiceResponse.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowTicketingTimeRepository.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/user-domain/src/main/java/org/example/config/UserDomainConfig.java
  app/domain/user-domain/src/main/java/org/example/dto/request/TicketingAlertReservationDomainRequest.java
  app/domain/user-domain/src/main/java/org/example/dto/response/TicketingAlertsDomainResponse.java
  app/domain/user-domain/src/main/java/org/example/entity/TicketingAlert.java
  app/domain/user-domain/src/main/java/org/example/repository/ticketing/TicketingAlertQuerydslRepository.java
  app/domain/user-domain/src/main/java/org/example/repository/ticketing/TicketingAlertQuerydslRepositoryImpl.java
  app/domain/user-domain/src/main/java/org/example/repository/ticketing/TicketingAlertRepository.java
  app/domain/user-domain/src/main/java/org/example/usecase/TicketingAlertUseCase.java
  app/domain/user-domain/src/main/java/org/example/vo/TicketingAlertTime.java
  app/domain/user-domain/src/main/java/org/example/vo/TicketingType.java
  app/infrastructure/message-queue/src/main/java/org/example/message/ReserveShowInfraMessage.java
  app/infrastructure/message-queue/src/main/java/org/example/message/TicketingReservationInfraMessage.java
  app/infrastructure/message-queue/src/main/java/org/example/publish/RedisMessagePublisher.java
Labels: feat

#108 feat: Image push to repository
  .github/workflows/showpot-prod-cd.yml
  app/domain/common-domain/src/main/resources/data.sql
  app/domain/common-domain/src/main/resources/schema.sql
  app/infrastructure/redis/src/main/java/org/example/config/RedisConfig.java
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-local.yml
  app/src/main/resources/application-prod.yml
  app/src/main/resources/logback-spring.xml
  docker-compose-prod.yml
  dockerfile-prod
Labels: feat

#114 feat: 티켓팅 알림 설정 후 종료된 공연 목록, 개수 API
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/param/ShowAlertPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowAlertPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TerminatedTicketingShowCountApiResponse.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/param/ShowAlertPaginationServiceParam.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowAlertPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/TerminatedTicketingShowCountServiceResponse.java
  app/api/show-api/src/main/java/com/example/show/vo/ShowTicketingAtStatusApiType.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowAlertPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowAlertDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/repository/show/showticketing/ShowTicketingTimeQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowTicketingTimeUseCase.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/show-domain/src/main/java/org/example/vo/ShowTicketingAtStatus.java
Labels: feat

#116 fix: 공연 업데이트 오류 문제
  app/api/common-api/src/main/java/org/example/error/GlobalExceptionHandler.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistAdminService.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistService.java
  app/api/show-api/src/main/java/com/example/genre/service/GenreAdminService.java
  app/api/show-api/src/main/java/com/example/show/service/ShowAdminService.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/test/java/show/service/ShowAdminServiceTest.java
  app/api/user-api/src/main/java/org/example/service/UserService.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowUpdateDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/entity/show/Show.java
  app/domain/show-domain/src/main/java/org/example/usecase/artist/ArtistUseCase.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowAdminUseCase.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  common/src/main/java/org/example/exception/GlobalError.java
Labels: fix

#118 fix: 공연 조회수 어뷰징 문제
  app/api/common-api/src/main/java/org/example/config/SecurityConfig.java
  app/api/show-api/src/main/java/com/example/component/ViewCountComponent.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/SeatTypePriceApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowDetailApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowTicketingSiteApiResponse.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/TicketingSiteApiResponse.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowTicketingSiteServiceResponse.java
  app/api/show-api/src/test/java/show/fixture/dto/ShowResponseDtoFixture.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/show-domain/build.gradle
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
  app/domain/user-domain/build.gradle
  app/infrastructure/redis/build.gradle
  app/infrastructure/redis/src/main/java/org/example/repository/RedisTokenRepository.java
  app/infrastructure/redis/src/main/java/org/example/repository/RedisViewCountComponent.java
Labels: fix

#124 fix: 아티스트 검색 응답 필드 수정
  app/api/show-api/src/main/java/com/example/artist/controller/ArtistController.java
  app/api/show-api/src/main/java/com/example/artist/controller/dto/param/ArtistSearchPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/artist/controller/dto/request/ArtistSearchPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/artist/service/ArtistService.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/param/ArtistSearchPaginationServiceParam.java
  app/api/show-api/src/main/java/com/example/artist/service/dto/request/ArtistSearchPaginationServiceRequest.java
  app/api/show-api/src/test/java/artist/service/ArtistServiceTest.java
  app/domain/show-domain/src/main/java/org/example/dto/artist/request/ArtistSearchPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/repository/artist/artistsearch/ArtistSearchQuerydslRepositoryImpl.java
  app/domain/user-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionRepository.java
  app/domain/user-domain/src/main/java/org/example/usecase/UserShowUseCase.java
Labels: fix

#127 fix: Update config
  .github/workflows/showpot-dev-cd.yml
  .github/workflows/showpot-dev-ci.yml
  .github/workflows/showpot-prod-cd.yml
  .github/workflows/showpot-prod-ci.yml
  app/src/main/resources/logback-spring.xml
  app/src/main/resources/logback-test.xml
Labels: fix

#130 fix: 티켓팅 메시지 publish 필드 수정
  app/api/show-api/src/main/java/com/example/publish/message/TicketingAlertsToReserveServiceMessage.java
  app/api/show-api/src/main/java/com/example/publish/message/TicketingTimeServiceMessage.java
  app/api/show-api/src/main/java/com/example/show/controller/vo/TicketingAlertTimeApiType.java
  app/domain/common-domain/src/main/resources/schema.sql
  app/domain/user-domain/src/main/java/org/example/dto/response/TicketingAlertsDomainResponse.java
  app/domain/user-domain/src/main/java/org/example/dto/response/TicketingTimeDomainResponse.java
  app/domain/user-domain/src/main/java/org/example/usecase/TicketingAlertUseCase.java
  app/domain/user-domain/src/main/java/org/example/vo/TicketingAlertTime.java
  app/infrastructure/message-queue/src/main/java/org/example/message/TicketingReservationInfraMessage.java
  app/infrastructure/message-queue/src/main/java/org/example/message/TicketingTimeInfraMessage.java
Labels: fix

#132 feat: 장르 전체 목록 조회 기능 구현
  app/api/show-api/src/main/java/com/example/genre/controller/GenreController.java
  app/api/show-api/src/main/java/com/example/genre/controller/dto/param/GenrePaginationApiParam.java
  app/api/show-api/src/main/java/com/example/genre/controller/dto/request/GenrePaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/genre/service/GenreService.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/param/GenrePaginationServiceParam.java
  app/api/show-api/src/main/java/com/example/genre/service/dto/request/GenrePaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/vo/SubscriptionStatusApiType.java
  app/domain/show-domain/src/main/java/org/example/repository/genre/GenreQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/vo/SubscriptionStatus.java
Labels: feat

#133 fix: 초기 데이터 수정
  app/domain/common-domain/src/main/resources/data.sql
Labels: fix

#136 fix: 공연 전체 목록 조회 기능 수정
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/request/ShowPaginationApiRequest.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowPaginationApiParam.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowPaginationServiceResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/request/ShowPaginationDomainRequest.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowTicketingDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/dto/show/response/ShowTicketingPaginationDomainResponse.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepository.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
  app/domain/show-domain/src/main/java/org/example/usecase/show/ShowUseCase.java
Labels: fix, feat

#137 feat: 데이터 삽입
  app/domain/common-domain/src/main/resources/data.sql
Labels: feat

#138 fix: 공연 목록 조회 쿼리 수정
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/request/ShowPaginationServiceRequest.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowPaginationServiceResponse.java
  app/domain/show-domain/src/main/java/org/example/repository/show/ShowQuerydslRepositoryImpl.java
Labels: fix

#140 fix: 공연 관심 설정 응답 필드 추가
  app/api/common-api/src/main/java/org/example/util/ValidatorUser.java
  app/api/show-api/src/main/java/com/example/show/controller/ShowController.java
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowDetailApiResponse.java
  app/api/show-api/src/main/java/com/example/show/service/ShowService.java
  app/api/show-api/src/main/java/com/example/show/service/dto/response/ShowDetailServiceResponse.java
  app/api/show-api/src/test/java/show/service/ShowServiceTest.java
  app/domain/user-domain/src/main/java/org/example/usecase/UserShowUseCase.java
Labels: fix

#141 fix: 공연 데이터 수정
  app/api/show-api/src/main/java/com/example/show/controller/dto/response/ShowInfoApiResponse.java
  app/domain/common-domain/src/main/resources/data.sql
Labels: fix

#142 refactor: 더미데이터 수정
  app/domain/common-domain/src/main/resources/data.sql
Labels: fix

#143 refactor: 닉네임 수정
  app/domain/user-domain/src/main/java/org/example/vo/RandomNickname.java
Labels: fix

#145 fix: 공연 검색 수정
  app/domain/common-domain/src/main/resources/data.sql
  app/domain/show-domain/src/main/java/org/example/repository/show/showsearch/ShowSearchQuerydslRepositoryImpl.java
Labels: fix
